version: "2"

services:

  spring-boot-reactive:
    build:
      context: ../spring-boot-reactive-web
    image: spring-boot-reactive-web-tpd
    # environment:
      # Overrides the host in the Spring Boot application to use the Docker's hostname
      # - SPRING_DATA_MONGODB_HOST=mongo
    ports:
      - "8080:8080"
    networks:
      - network-reactive

  angular-reactive:
    build:
      context: ../angular-reactive
    image: angular-reactive-tpd
    ports:
      - "8900:80"
    networks:
      - network-reactive



networks:
  network-reactive: